"""

Configuration Module for API Dock

Handles loading and parsing of YAML configuration files for main API and remote APIs.

License: BSD 3-Clause

"""

#
# IMPORTS
#
import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import yaml


#
# CONSTANTS
#
DEFAULT_CONFIG_DIR: str = "api_dock_config"
DEFAULT_CONFIG_FILE: str = "config.yaml"
REMOTES_DIR: str = "remotes"
DATABASES_DIR: str = "databases"
REMOTES_SHARED_FILE: str = "config.yaml"
REMOTE_CONFIGS_KEY: str = "remotes"
REMOTE_VERSION_KEY: str = "version"
REMOTE_VERSIONS_KEY: str = "versions"
VERSION_TOKEN_PATTERN: str = r"\d+|[A-Za-z]+"

# {{name}} or {name} in a remote route mapping.
ROUTE_PARAM_PATTERN: re.Pattern = re.compile(r"\{\{([^{}]+)\}\}|\{([^{}]+)\}")

# Marks remote versions generated by a lookup until get_inline_remote_configs.
GENERATED_FLAG: str = "__generated__"

# Default settings
DEFAULT_SETTINGS: Dict[str, Any] = {
    "add_trailing_slash": True,
}

# Default authentication and cookie settings
DEFAULT_AUTH_SETTINGS: Dict[str, Any] = {
    "encrypted": True  # Authentication values are encrypted by default
}

logger = logging.getLogger(__name__)


#
# PUBLIC
#
def load_main_config(config_path: Optional[str] = None) -> Dict[str, Any]:
    """Load the main configuration file.

    Args:
        config_path: Path to config file. If None, uses default path.

    Returns:
        Dictionary containing configuration data.

    Raises:
        FileNotFoundError: If config file doesn't exist.
        yaml.YAMLError: If config file is invalid YAML.
    """
    if config_path is None:
        config_path = os.path.join(DEFAULT_CONFIG_DIR, DEFAULT_CONFIG_FILE)

    return load_yaml_file(config_path)


def find_remote_config(remote_name: str, main_config: Dict[str, Any], config_dir: Optional[str] = None, version: Optional[str] = None) -> Dict[str, Any]:
    """Find and load configuration for a specific remote API by name.

    Args:
        remote_name: Name of the remote (from the name field in YAML).
        main_config: Main configuration dictionary.
        config_dir: Base config directory. If None, uses default.
        version: Version string for versioned remotes (e.g., "0.1", "1.2"). If None, loads non-versioned or latest version.

    Returns:
        Dictionary containing remote configuration data.

    Raises:
        FileNotFoundError: If remote config file doesn't exist.
        yaml.YAMLError: If config file is invalid YAML.
    """
    if config_dir is None:
        config_dir = DEFAULT_CONFIG_DIR

    # Check if this is a versioned remote
    if is_versioned_remote(remote_name, main_config, config_dir):
        if version is None:
            raise FileNotFoundError(f"Remote '{remote_name}' is versioned - version parameter required")

        # A version file wins over an entry in remotes/config.yaml
        config_path = os.path.join(config_dir, REMOTES_DIR, remote_name, f"{version}.yaml")
        if os.path.isfile(config_path):
            return _fill_lookup_values(load_yaml_file(config_path), config_path, config_dir)
        inline_versions = get_inline_remote_configs(config_dir).get(remote_name, {})
        if str(version) in inline_versions:
            return inline_versions[str(version)]
        raise FileNotFoundError(f"Remote '{remote_name}' has no version '{version}'")

    # Non-versioned remote - use the regular mapping
    remote_mapping = get_remote_mapping(main_config, config_dir)

    if remote_name not in remote_mapping:
        raise FileNotFoundError(f"Remote '{remote_name}' not found in configuration")

    config_path = remote_mapping[remote_name]

    if config_path is not None and os.path.isfile(config_path):
        return _fill_lookup_values(load_yaml_file(config_path), config_path, config_dir)
    inline_versions = get_inline_remote_configs(config_dir).get(remote_name, {})
    if None in inline_versions:
        return inline_versions[None]
    raise FileNotFoundError(f"No config file or remotes/config.yaml entry for remote '{remote_name}'")


def get_remote_mapping(config: Dict[str, Any], config_dir: Optional[str] = None) -> Dict[str, str]:
    """Create mapping from remote names to config file paths.

    Args:
        config: Main configuration dictionary.
        config_dir: Base config directory. If None, uses default.

    Returns:
        Dictionary mapping remote names to their config file paths. A remote
        without a file (defined only in ``remotes/config.yaml``) maps to the
        path its file would have; ``find_remote_config`` falls back to the
        inline entry when that file is missing.
    """
    if config_dir is None:
        config_dir = DEFAULT_CONFIG_DIR

    remotes = config.get("remotes", [])
    remote_mapping = {}

    for remote in remotes:
        if isinstance(remote, str):
            # String format: use filename as fallback
            filename = remote
            config_path = os.path.join(config_dir, REMOTES_DIR, f"{filename}.yaml")

            # Try to load the config to get the actual name
            try:
                remote_config = load_yaml_file(config_path)
                actual_name = remote_config.get("name", filename)
                remote_mapping[actual_name] = config_path
            except (FileNotFoundError, Exception):
                # If config can't be loaded, use filename as name
                remote_mapping[filename] = config_path

        elif isinstance(remote, dict) and "name" in remote:
            # Dict format: use the name directly
            remote_mapping[remote["name"]] = None  # Handle inline configs later if needed

    return remote_mapping


def get_remote_names(config: Dict[str, Any], config_dir: Optional[str] = None) -> List[str]:
    """Extract list of remote names from main config.

    Args:
        config: Main configuration dictionary.
        config_dir: Base config directory. If None, uses default.

    Returns:
        List of remote names.
    """
    return list(get_remote_mapping(config, config_dir).keys())


def get_database_names(config: Dict[str, Any], config_dir: Optional[str] = None) -> List[str]:
    """Extract list of database names from main config.

    An entry ``{from: <lookup>}`` stands for every database name that lookup's
    ``from:`` entries in ``databases/config.yaml`` generate (it follows the
    lookup's rows).

    Args:
        config: Main configuration dictionary.
        config_dir: Base config directory (for ``from:`` entries). If None,
            uses default.

    Returns:
        List of database names, without duplicates.
    """
    databases = config.get("databases", [])
    database_names: List[str] = []

    for database in databases:
        if isinstance(database, str):
            names = [database]
        elif isinstance(database, dict) and "name" in database:
            names = [database["name"]]
        elif isinstance(database, dict) and "from" in database:
            from api_dock.database_config import generated_database_names
            names = generated_database_names(database["from"], config_dir)
        else:
            names = []
        database_names.extend(name for name in names if name not in database_names)

    return database_names


def get_settings(config: Dict[str, Any]) -> Dict[str, Any]:
    """Extract settings from main config with defaults.

    Args:
        config: Main configuration dictionary.

    Returns:
        Dictionary of settings with defaults applied.
    """
    settings = DEFAULT_SETTINGS.copy()
    config_settings = config.get("settings", {})

    # Update defaults with config values
    if config_settings:
        settings.update(config_settings)

    return settings


def get_cookies_config(config: Dict[str, Any]) -> List[str]:
    """Extract cookie names to forward from incoming requests.

    Only string entries in the ``cookies`` list are returned here. Dict entries
    (cookie injection) are handled separately by ``resolve_inject_cookies``.

    Args:
        config: Configuration dictionary (main, remote, or database).

    Returns:
        List of cookie names to extract from requests.
    """
    cookies = config.get("cookies", [])
    if not isinstance(cookies, list):
        return []

    return [str(c) for c in cookies if c and isinstance(c, str)]


def filter_cookies_by_config(cookies: Dict[str, str], config: Dict[str, Any]) -> Dict[str, str]:
    """Filter incoming cookies based on configuration.

    Args:
        cookies: Dictionary of all incoming cookies.
        config: Configuration dictionary (main, remote, or database).

    Returns:
        Filtered dictionary of cookies.
    """
    cookies_setting = config.get("cookies")

    # Get authentication key if it exists
    auth_config = get_authentication_config(config)
    auth_key = auth_config.get("key") if auth_config else None

    # Handle boolean settings
    if isinstance(cookies_setting, bool):
        if cookies_setting:
            # cookies: true - pass all cookies
            return cookies
        else:
            # cookies: false - pass no cookies except authentication key
            if auth_key and auth_key in cookies:
                auth_only = {auth_key: cookies[auth_key]}
                return auth_only
            else:
                return {}

    # Handle list — may contain string names (forward from client) and/or
    # dict entries (inject from config/env var).
    elif isinstance(cookies_setting, list):
        injected = resolve_inject_cookies(config)
        allowed_cookies = get_cookies_config(config)

        if not allowed_cookies:
            # No string entries — only auth key forwarded from client, plus injected.
            result: Dict[str, str] = {}
            if auth_key and auth_key in cookies:
                result[auth_key] = cookies[auth_key]
            result.update(injected)
            return result

        # Always include authentication key in forwarded set.
        if auth_key and auth_key not in allowed_cookies:
            allowed_cookies = allowed_cookies + [auth_key]

        filtered = {k: v for k, v in cookies.items() if k in allowed_cookies}
        filtered.update(injected)
        return filtered

    # Default: no cookie configuration means only authentication key passed
    else:
        if auth_key and auth_key in cookies:
            auth_only = {auth_key: cookies[auth_key]}
            return auth_only
        else:
            return {}


def resolve_inject_cookies(config: Dict[str, Any]) -> Dict[str, str]:
    """Resolve dict entries in the ``cookies`` list into ready-to-send cookie values.

    The ``cookies`` list accepts a mix of strings (names of client cookies to forward)
    and dicts (cookies to inject into the outgoing request regardless of what the
    client sent). This function handles the dict entries only.

    Dict entry forms:

    - ``{key: COOKIE_NAME, value: "literal-value"}`` — inject with a literal string.
    - ``{key: COOKIE_NAME, value: "env:MY_ENV_VAR"}`` — inject with the value of
      environment variable ``MY_ENV_VAR``; resolves to empty string if unset.
    - ``{key: MY_ENV_VAR}`` — shorthand: no ``value`` means look up an env var whose
      name equals the key (equivalent to ``{key: MY_ENV_VAR, value: "env:MY_ENV_VAR"}``).

    Example YAML::

        cookies:
          - session_id                           # forward from client request
          - key: __Secure-authjs.session-token
            value: "env:SOUNDHUB_SESSION_TOKEN"  # inject from env var

    Args:
        config: Configuration dictionary (main, remote, or database).

    Returns:
        Dictionary mapping cookie names to their resolved string values.
    """
    cookies_setting = config.get("cookies", [])
    if not isinstance(cookies_setting, list):
        return {}

    result: Dict[str, str] = {}
    for entry in cookies_setting:
        if not isinstance(entry, dict):
            continue
        key = entry.get("key")
        if not key or not isinstance(key, str):
            continue
        raw_value = entry.get("value")
        if raw_value is None:
            value = os.environ.get(key, "")
        elif isinstance(raw_value, str) and raw_value.startswith("env:"):
            value = os.environ.get(raw_value[4:], "")
        else:
            value = str(raw_value)
        result[key] = value
    return result


def get_authentication_config(config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Extract authentication configuration from config.

    Args:
        config: Configuration dictionary (main, remote, or database).

    Returns:
        Authentication configuration dictionary, or None if not configured.
    """
    auth_config = config.get("authentication")
    if not auth_config:
        return None

    if not isinstance(auth_config, dict):
        return None

    # Apply default encryption setting if not specified
    auth_config = auth_config.copy()
    if "encrypted" not in auth_config:
        auth_config["encrypted"] = DEFAULT_AUTH_SETTINGS["encrypted"]

    return auth_config


def merge_inherited_config(child_config: Dict[str, Any], parent_config: Dict[str, Any]) -> Dict[str, Any]:
    """Merge child configuration with parent configuration for inheritance.

    Cookies and authentication from parent are inherited by child unless explicitly overridden.

    Args:
        child_config: Child configuration (remote or database specific).
        parent_config: Parent configuration (main config).

    Returns:
        Merged configuration with inheritance applied.
    """
    merged = child_config.copy()

    # Inherit cookies if not specified in child
    if "cookies" not in merged and "cookies" in parent_config:
        merged["cookies"] = parent_config["cookies"]

    # Inherit authentication if not specified in child
    if "authentication" not in merged and "authentication" in parent_config:
        merged["authentication"] = parent_config["authentication"]

    return merged


def validate_authentication_config(auth_config: Dict[str, Any]) -> bool:
    """Validate authentication configuration.

    Args:
        auth_config: Authentication configuration dictionary.

    Returns:
        True if valid, False otherwise.
    """
    if not isinstance(auth_config, dict):
        return False

    # Must have a key field
    if "key" not in auth_config or not auth_config["key"]:
        return False

    # Must have a valid method
    valid_methods = ["fixed", "list", "aws_secrets", "gcp_secrets"]
    method = auth_config.get("method")
    if method not in valid_methods:
        return False

    # Validate method-specific fields
    if method == "fixed":
        if "value" not in auth_config:
            return False
    elif method == "list":
        values = auth_config.get("values")
        if not isinstance(values, list) or not values:
            return False
    elif method == "aws_secrets":
        if "secret_name" not in auth_config:
            return False
        # Region is optional (can use default from environment)
    elif method == "gcp_secrets":
        if "secret_name" not in auth_config or "project_id" not in auth_config:
            return False

    return True


def validate_cookies_config(cookies_config: List[str]) -> bool:
    """Validate cookies configuration.

    Args:
        cookies_config: List of cookie names.

    Returns:
        True if valid, False otherwise.
    """
    if not isinstance(cookies_config, list):
        return False

    # All cookie names must be valid identifiers
    for cookie_name in cookies_config:
        if not isinstance(cookie_name, str) or not cookie_name:
            return False
        # Cookie names should be valid identifiers (alphanumeric + underscore)
        if not cookie_name.replace("_", "").replace("-", "").isalnum():
            return False

    return True


def is_versioned_remote(remote_name: str, main_config: Dict[str, Any], config_dir: Optional[str] = None) -> bool:
    """Check if a remote has versioned configurations.

    Args:
        remote_name: Name of the remote.
        main_config: Main configuration dictionary.
        config_dir: Base config directory. If None, uses default.

    Returns:
        True if the remote has a config directory or versioned entries in
        ``remotes/config.yaml``, False otherwise.

    Raises:
        ValueError: If ``remotes/config.yaml`` is malformed.
    """
    if config_dir is None:
        config_dir = DEFAULT_CONFIG_DIR

    remote_dir = os.path.join(config_dir, REMOTES_DIR, remote_name)
    if os.path.isdir(remote_dir):
        return True
    return any(v is not None for v in get_inline_remote_configs(config_dir).get(remote_name, {}))


def get_remote_versions(remote_name: str, main_config: Dict[str, Any], config_dir: Optional[str] = None) -> List[str]:
    """Get list of available versions for a versioned remote.

    Args:
        remote_name: Name of the remote.
        main_config: Main configuration dictionary.
        config_dir: Base config directory. If None, uses default.

    Returns:
        Version strings from version files and ``remotes/config.yaml``, without
        duplicates, lowest first (see ``sort_versions``). Returns an empty list
        if the remote is not versioned.

    Raises:
        ValueError: If ``remotes/config.yaml`` is malformed.
    """
    if config_dir is None:
        config_dir = DEFAULT_CONFIG_DIR

    if not is_versioned_remote(remote_name, main_config, config_dir):
        return []

    remote_dir = os.path.join(config_dir, REMOTES_DIR, remote_name)
    versions = set()

    if os.path.isdir(remote_dir):
        for filename in os.listdir(remote_dir):
            if filename.endswith('.yaml'):
                versions.add(filename[:-5])  # Remove .yaml extension

    inline_versions = get_inline_remote_configs(config_dir).get(remote_name, {})
    versions.update(v for v in inline_versions if v is not None)

    return sort_versions(versions)


def load_shared_remote_config(config_dir: Optional[str] = None) -> Dict[str, Any]:
    """Load the shared remote config (``remotes/config.yaml``) with lookups applied.

    A remote's ``versions`` may have ``{from: <lookup>, ...}`` entries (one
    version per row, ``{{row.<column>}}`` filled in), and any value outside
    routes may be ``{{lookup.<name>.<column>}}``. Memoized on the file and the
    lookup rows.

    Args:
        config_dir: Base config directory. If None, uses default.

    Returns:
        The expanded file contents (see load_static_remote_config); generated
        version entries carry GENERATED_FLAG until get_inline_remote_configs.

    Raises:
        yaml.YAMLError: If the file exists but is invalid YAML.
        ValueError: If the file is invalid, a template is misplaced, or a
            ``{{lookup.*}}`` value can't be filled.
    """
    from api_dock.lookups import file_key, get_store, memoized

    if config_dir is None:
        config_dir = DEFAULT_CONFIG_DIR
    shared_path = os.path.join(config_dir, REMOTES_DIR, REMOTES_SHARED_FILE)
    store = get_store(config_dir)
    return memoized(
        ("remotes", file_key(shared_path), store.generation),
        lambda: _expand_remote_config(load_static_remote_config(config_dir), store, shared_path),
    )


def load_static_remote_config(config_dir: Optional[str] = None) -> Dict[str, Any]:
    """Load the optional shared remote config (``remotes/config.yaml``) as written.

    Args:
        config_dir: Base config directory. If None, uses default.

    Returns:
        The file's contents with ``remotes`` normalized to a mapping and
        ``lookups`` parsed into LookupSpecs, or an empty dict if the file
        doesn't exist.

    Raises:
        yaml.YAMLError: If the file exists but is invalid YAML.
        ValueError: If the file, its ``remotes`` key or a lookup is invalid.
    """
    from api_dock.lookups import LOOKUPS_KEY, parse_lookups

    if config_dir is None:
        config_dir = DEFAULT_CONFIG_DIR

    shared_path = os.path.join(config_dir, REMOTES_DIR, REMOTES_SHARED_FILE)
    if not os.path.isfile(shared_path):
        return {}

    contents = load_yaml_file(shared_path) or {}
    if not isinstance(contents, dict):
        raise ValueError(f"{shared_path} must contain a mapping")
    remotes = contents.get(REMOTE_CONFIGS_KEY) or {}
    if not isinstance(remotes, dict):
        raise ValueError(f"'{REMOTE_CONFIGS_KEY}' in {shared_path} must be a mapping of name -> config")
    return {
        **contents,
        REMOTE_CONFIGS_KEY: remotes,
        LOOKUPS_KEY: parse_lookups(contents.get(LOOKUPS_KEY), shared_path),
    }


def get_inline_remote_configs(config_dir: Optional[str] = None) -> Dict[str, Dict[Optional[str], Dict[str, Any]]]:
    """Build remote configs from the ``remotes`` mapping in ``remotes/config.yaml``.

    Each key is a remote name and each value a remote config (url, description,
    routes, restricted, cookies, ...) with one of:
      - ``version: <v>``: one versioned config;
      - ``versions: [{version: <v>, ...}, ...]``: several versions, where the
        entry's other keys are defaults each version's keys override;
      - neither: an unversioned remote.

    Args:
        config_dir: Base config directory. If None, uses default.

    Returns:
        Mapping of remote name -> {version string (None if unversioned) ->
        remote config dict}. Versions are strings (YAML ``1.0`` -> "1.0").

    Raises:
        ValueError: If an entry is malformed, uses both ``version`` and
            ``versions``, or defines the same version twice.
    """
    remotes = load_shared_remote_config(config_dir).get(REMOTE_CONFIGS_KEY) or {}
    configs: Dict[str, Dict[Optional[str], Dict[str, Any]]] = {}

    for raw_name, entry in remotes.items():
        name = str(raw_name)
        label = f"remotes/{REMOTES_SHARED_FILE}: '{name}'"
        if not isinstance(entry, dict):
            raise ValueError(f"{label} must be a mapping")
        if REMOTE_VERSION_KEY in entry and REMOTE_VERSIONS_KEY in entry:
            raise ValueError(f"{label} uses both '{REMOTE_VERSION_KEY}' and '{REMOTE_VERSIONS_KEY}'")

        defaults = {
            k: v for k, v in entry.items() if k not in (REMOTE_VERSION_KEY, REMOTE_VERSIONS_KEY)
        }
        if REMOTE_VERSIONS_KEY in entry:
            version_entries = entry[REMOTE_VERSIONS_KEY]
            if not isinstance(version_entries, list) or not version_entries:
                raise ValueError(f"{label} '{REMOTE_VERSIONS_KEY}' must be a non-empty list")
            # Static versions first, so a generated (lookup) version never replaces one.
            version_entries = sorted(
                version_entries,
                key=lambda e: isinstance(e, dict) and bool(e.get(GENERATED_FLAG)),
            )
        else:
            version_entries = [{REMOTE_VERSION_KEY: entry.get(REMOTE_VERSION_KEY)}]

        versions = configs.setdefault(name, {})
        for version_entry in version_entries:
            if not isinstance(version_entry, dict):
                raise ValueError(f"{label} has an invalid version entry: {version_entry!r}")
            raw_version = version_entry.get(REMOTE_VERSION_KEY)
            if REMOTE_VERSIONS_KEY in entry and raw_version is None:
                raise ValueError(f"{label} has a version entry without a version")
            version = None if raw_version is None else str(raw_version).strip()
            generated = bool(version_entry.get(GENERATED_FLAG))
            if version in versions:
                if not generated:
                    raise ValueError(f"{label} version {version} is defined twice")
                logger.warning("%s version %s is defined twice (generated by a lookup); "
                               "kept the first", label, version)
                continue
            own = {
                k: v for k, v in version_entry.items()
                if k not in (REMOTE_VERSION_KEY, GENERATED_FLAG)
            }
            versions[version] = {"name": name, **defaults, **own}

    return configs


def version_sort_key(version: str) -> tuple:
    """Sort key that orders version strings the way people read them.

    Digit runs compare as numbers and letter runs as text, with text lower
    than numbers, so "0.10" > "0.9", "1.0.0" > "1.0", "2.0" > "2.0rc1" and
    "v10" > "v9". Separators are ignored; the full string breaks ties.

    Args:
        version: A version string (e.g. "0.5.0").

    Returns:
        A tuple usable as a sort key.
    """
    tokens = re.findall(VERSION_TOKEN_PATTERN, str(version))
    # Ranks: text (pre-release) < end of version < number
    parts = tuple((2, int(t), "") if t.isdigit() else (0, 0, t.lower()) for t in tokens)
    return parts + ((1, 0, ""),), str(version)


def sort_versions(versions: Any) -> List[str]:
    """Sort version strings lowest first, using ``version_sort_key``.

    Args:
        versions: An iterable of version strings.

    Returns:
        The versions as a sorted list.
    """
    return sorted(versions, key=version_sort_key)


def load_yaml_file(file_path: str, kind: str = "Configuration") -> Any:
    """Load a YAML file (an empty file loads as an empty mapping).

    Args:
        file_path: Path to the YAML file.
        kind: What the file is, for the not-found message.

    Returns:
        The file's contents.

    Raises:
        FileNotFoundError: If the file doesn't exist.
        yaml.YAMLError: If the file is invalid YAML.
    """
    try:
        with open(file_path, 'r') as file:
            return yaml.safe_load(file) or {}
    except FileNotFoundError:
        raise FileNotFoundError(f"{kind} file not found: {file_path}")
    except yaml.YAMLError as error:
        raise yaml.YAMLError(f"Invalid YAML in {file_path}: {error}")


def versions_equal(version: Any, spec: Any) -> bool:
    """Whether two version values name the same version.

    Compared part by part with numbers as numbers, ignoring trailing ``.0``
    parts, so "3", "3.0" and a YAML ``3.0`` match, while "1.10" and "1.1" don't.

    Args:
        version: A version (e.g. a file name stem).
        spec: A configured version (string or YAML number).

    Returns:
        True if they name the same version.
    """
    def parts(value: Any) -> tuple:
        tokens = list(version_sort_key(str(value).strip())[0][:-1])
        while tokens and tokens[-1] == (2, 0, ""):
            tokens.pop()
        return tuple(tokens)
    return str(version).strip() == str(spec).strip() or parts(version) == parts(spec)


def resolve_latest_version(versions: List[str]) -> Optional[str]:
    """Resolve 'latest' to the highest version from a list.

    Args:
        versions: List of version strings.

    Returns:
        The latest version string (see ``version_sort_key``), or None if the
        list is empty.
    """
    if not versions:
        return None
    return max(versions, key=version_sort_key)


def is_route_allowed(route: str, config: Dict[str, Any], remote_name: Optional[str] = None, version: Optional[str] = None, method: Optional[str] = None, config_dir: Optional[str] = None) -> bool:
    """Check if a route is allowed based on configuration restrictions.

    Args:
        route: The route to check (e.g., "users/123/delete").
        config: Main configuration dictionary.
        remote_name: Name of the remote API (for remote-specific restrictions).
        version: Version string for versioned remotes.
        method: HTTP method (e.g., "GET", "POST", "DELETE").
        config_dir: Directory holding the main config (remote files are read
            from its remotes/ folder). If None, uses default.

    Returns:
        True if route is allowed, False otherwise.
    """
    # Always allow empty route (root path) for API metadata access
    if not route or route == "":
        return True
    # Check global restrictions from main config
    global_restricted = config.get("restricted", [])
    global_routes = config.get("routes", [])

    # Check remote-specific restrictions from remote config file
    remote_restricted = []
    remote_routes = []

    if remote_name:
        try:
            remote_config = find_remote_config(remote_name, config, config_dir=config_dir, version=version)
            remote_restricted = remote_config.get("restricted", [])
            remote_routes = remote_config.get("routes", [])
        except FileNotFoundError:
            # If remote config not found, just use global restrictions
            pass

    # If explicit routes are defined (whitelist), check against them
    # Remote-specific routes take precedence over global routes
    allowed_routes = remote_routes if remote_routes else global_routes
    if allowed_routes:
        # Check whitelist first
        if not _route_matches_patterns(route, allowed_routes, method):
            return False
        # Even if route is in whitelist, still check restrictions (both global and remote)
        all_restrictions = global_restricted + remote_restricted
        if all_restrictions and _route_matches_patterns(route, all_restrictions, method):
            return False
        return True

    # Otherwise, check against restricted patterns (blacklist)
    # Combine both global and remote restrictions
    all_restrictions = global_restricted + remote_restricted
    if all_restrictions:
        return not _route_matches_patterns(route, all_restrictions, method)

    # If no restrictions, allow all routes
    return True


def find_route_mapping(full_route: str, method: str, remote_config: Dict[str, Any], remote_name: str, cookies: Optional[Dict[str, str]] = None) -> Optional[str]:
    """Find custom route mapping for a specific route and method.

    Args:
        full_route: The incoming route with remote name (e.g., "another_name/users/123/permissions").
        method: HTTP method (e.g., "GET", "POST").
        remote_config: Remote configuration dictionary.
        remote_name: Name of the remote for route_name substitution.
        cookies: Cookie values from request for substitution.

    Returns:
        Mapped remote route if found, None otherwise.
    """
    routes = remote_config.get("routes", [])

    for route_mapping in routes:
        if isinstance(route_mapping, dict):
            config_route = route_mapping.get("route", "")
            config_method = route_mapping.get("method", "").upper()
            remote_route = route_mapping.get("remote_route", "")

            # Check if method matches (case insensitive)
            if config_method and config_method != method.upper():
                continue

            # Replace {{route_name}} with actual remote name in the pattern
            pattern_with_name = config_route.replace("{{route_name}}", remote_name)

            # Check if route pattern matches and extract parameters
            params = _extract_route_params(full_route, pattern_with_name)
            if params is not None:
                # Add route_name to parameters for substitution
                params["route_name"] = remote_name

                # Add cookies with "cookies." prefix for substitution
                if cookies:
                    for cookie_key, cookie_value in cookies.items():
                        params[f"cookies.{cookie_key}"] = cookie_value

                # Substitute parameters in remote_route
                return _substitute_route_params(remote_route, params)

    return None


def filter_remote_query_params(
    query_params: Dict[str, Any],
    route: str,
    method: str,
    remote_config: Dict[str, Any]
) -> Dict[str, Any]:
    """Filter query parameters based on remote config settings.

    Checks for a route-level query_params setting first, then falls back
    to the top-level remote config query_params. If neither exists, all
    params are passed through unchanged (backward compatible).

    Filtering is by key only, so values may be strings or lists of strings
    (the latter forwarding repeated keys such as ?id=1&id=2 intact).

    Args:
        query_params: Original query parameters from the request. Values may be
            strings or lists of strings.
        route: The actual route path (e.g., "users/123").
        method: HTTP method (e.g., "GET", "POST").
        remote_config: Remote configuration dictionary.

    Returns:
        Filtered query parameters dictionary (value types preserved).
    """
    routes = remote_config.get("routes", [])

    # Find matching route and its query_params setting
    route_query_params_setting = None
    for route_entry in routes:
        if isinstance(route_entry, str):
            if _route_matches_pattern(route, route_entry):
                # String routes have no query_params setting
                break
        elif isinstance(route_entry, dict):
            if _route_matches_pattern(route, route_entry, method):
                route_query_params_setting = route_entry.get("query_params")
                break

    # Fall back to top-level setting if route has no query_params key
    if route_query_params_setting is None:
        setting = remote_config.get("query_params")
    else:
        setting = route_query_params_setting

    # No setting anywhere → pass all params through (backward compatible)
    if setting is None:
        return query_params

    # True → all params
    if setting is True:
        return query_params

    # False → no params
    if setting is False:
        return {}

    # List → whitelist filter
    if isinstance(setting, list):
        return {k: v for k, v in query_params.items() if k in setting}

    # Unknown type → pass all through
    return query_params


#
# INTERNAL
#
def _expand_remote_config(static: Dict[str, Any], store: Any, label: str) -> Dict[str, Any]:
    """Apply lookup rows to a shared remote config (see load_shared_remote_config).

    Args:
        static: The file as written (load_static_remote_config).
        store: The LookupStore.
        label: The file path (for messages).

    Returns:
        The expanded contents.

    Raises:
        ValueError: If a template is misplaced or a ``{{lookup.*}}`` value
            can't be filled.
    """
    from api_dock.lookups import (
        check_plain, expand_entries, fill_templates, generated_versions, LOOKUPS_KEY,
    )

    if not static:
        return static

    def check_generated(entry: Dict[str, Any]) -> None:
        entry[REMOTE_VERSION_KEY] = check_plain(entry.get(REMOTE_VERSION_KEY), "version")
        entry[GENERATED_FLAG] = True

    remotes = {}
    for name, entry in (static.get(REMOTE_CONFIGS_KEY) or {}).items():
        if not isinstance(entry, dict):
            remotes[name] = entry
            continue
        versions = generated_versions(entry.get(REMOTE_VERSIONS_KEY))
        entry_label = f"{label}: remote '{name}'"
        filled = dict(_fill_lookup_values(
            {k: v for k, v in entry.items() if versions is None or k != REMOTE_VERSIONS_KEY},
            entry_label, store.config_dir,
        ))
        if versions is not None:
            filled[REMOTE_VERSIONS_KEY] = [
                version if origin is not None else fill_templates(version, None, store)
                for version, origin in expand_entries(
                    versions, store, f"{entry_label} versions", check_generated
                )
            ]
            if not filled[REMOTE_VERSIONS_KEY]:
                continue
        remotes[name] = filled
    return {**static, REMOTE_CONFIGS_KEY: remotes, LOOKUPS_KEY: static.get(LOOKUPS_KEY) or {}}


def _fill_lookup_values(config: Any, label: str, config_dir: Optional[str]) -> Any:
    """Fill ``{{lookup.*}}`` values in a remote config (see database_config.fill_lookup_values).

    Args:
        config: The loaded config.
        label: Where it came from (for messages).
        config_dir: Base config directory.

    Returns:
        The filled config.

    Raises:
        ValueError: If a template is misplaced or a value can't be filled.
    """
    from api_dock.database_config import fill_lookup_values
    return fill_lookup_values(config, label, config_dir)


def _route_matches_patterns(route: str, patterns: List[Union[str, dict]], method: Optional[str] = None) -> bool:
    """Check if a route matches any of the given patterns.

    Args:
        route: The route to check.
        patterns: List of patterns to match against (strings or dicts with route/method).
        method: HTTP method to check (optional).

    Returns:
        True if route matches any pattern, False otherwise.
    """
    for pattern in patterns:
        if _route_matches_pattern(route, pattern, method):
            return True
    return False


def _route_matches_pattern(route: str, pattern: Union[str, dict], method: Optional[str] = None) -> bool:
    """Check if a route matches a specific pattern.

    Patterns use {{}} or * as wildcards for path segments.
    Supports method-specific matching when pattern is a dict.
    Examples:
        - "users/{{}}/delete" matches "users/123/delete"
        - "users/*/delete" matches "users/123/delete"
        - "users/*" matches "users/123", "users/123/profile", etc. (prefix match)
        - {"route": "users/*", "method": "delete"} matches DELETE to "users/123"
        - "*" matches any single segment route
        - {"route": "*", "method": "delete"} matches DELETE to ANY route (all routes)

    Args:
        route: The route to check.
        pattern: The pattern to match against (string or dict with route/method).
        method: HTTP method to check (optional, used with dict patterns).

    Returns:
        True if route matches pattern, False otherwise.
    """
    # Handle dict format (with method specified)
    is_method_aware = False
    if isinstance(pattern, dict):
        pattern_route = pattern.get("route", "")
        pattern_method = pattern.get("method", "").upper() if pattern.get("method") else None

        # If method specified in pattern, it must match
        if pattern_method and method and pattern_method != method.upper():
            return False

        is_method_aware = True
        pattern = pattern_route

    # Handle case where pattern is not a string at this point
    if not isinstance(pattern, str):
        return False

    # Handle trailing wildcard for prefix matching
    if pattern.endswith("/*"):
        prefix = pattern[:-2].strip("/")
        route_normalized = route.strip("/")

        # Empty prefix means match everything
        if not prefix:
            return True

        return route_normalized.startswith(prefix + "/") or route_normalized == prefix

    # Handle exact wildcard match
    if pattern.strip("/") == "*":
        # When used with method restriction (dict format), * matches ALL routes
        # When used alone (string format), * matches only single-segment routes
        if is_method_aware:
            return True  # Match all routes when method-aware
        else:
            return len(route.strip("/").split("/")) == 1  # Match only single-segment routes

    route_parts = route.strip("/").split("/")
    pattern_parts = pattern.strip("/").split("/")

    if len(route_parts) != len(pattern_parts):
        return False

    for route_part, pattern_part in zip(route_parts, pattern_parts):
        # Check if pattern part is a wildcard
        if pattern_part == "*" or (pattern_part.startswith("{{") and pattern_part.endswith("}}")):
            # Wildcard matches any value
            continue
        elif pattern_part != route_part:
            # Literal part must match exactly
            return False

    return True


def _extract_route_params(actual_route: str, pattern_route: str) -> Optional[Dict[str, str]]:
    """Extract parameters from an actual route using a pattern.

    Args:
        actual_route: The actual route (e.g., "users/123/permissions").
        pattern_route: The pattern route (e.g., "users/{user_id}/permissions").

    Returns:
        Dictionary of parameter mappings if match, None otherwise.
    """
    actual_parts = actual_route.strip("/").split("/")
    pattern_parts = pattern_route.strip("/").split("/")

    if len(actual_parts) != len(pattern_parts):
        return None

    params = {}
    for actual_part, pattern_part in zip(actual_parts, pattern_parts):
        if pattern_part.startswith("{") and pattern_part.endswith("}"):
            # {name} or {{name}}
            params[pattern_part.strip("{}").strip()] = actual_part
        elif pattern_part != actual_part:
            # Fixed path segment doesn't match
            return None

    return params


def _substitute_route_params(template_route: str, params: Dict[str, str]) -> str:
    """Substitute parameters in a template route.

    Args:
        template_route: The template route (e.g., "user-permissions/{{user_id}}").
        params: Dictionary of parameter values.

    Returns:
        Route with substituted parameters.
    """
    def value(match: re.Match) -> str:
        name = (match.group(1) or match.group(2)).strip()
        return str(params[name]) if name in params else match.group(0)

    # {{name}} and {name}, in one pass (so a value is never substituted again)
    return ROUTE_PARAM_PATTERN.sub(value, template_route)
